### ISSUE TITLE
SSD Temperature_Celsius not detect

### ISSUE THREAD

**Issue by istoph** [zabbix-deb/zabbix-check-smart#3]
My SSD Smart inflammations for Temperature_Celsius are: 
```
194 Temperature_Celsius     0x0022   049   068   000    Old_age   Always       -       49 (Min/Max 32/68)
231 Temperature_Celsius     0x0000   099   099   000    Old_age   Offline      -       99
```

zabbix_get print:
```
zabbix_get -s host -k smart.raw[sdf,Temperature_Celsius]
50
99
```

Zabbix can only work with one attribute.

**Comment by imolein** [comment]
According to the manual we only want the Always value, because this is updated every time smartctl is running. The one with the value Offline is updated only during off-line data collection activities, like self-test.

**Comment by imolein** [comment]
zabbix-check-smart now detects only values from attributes which has UPDATED Always. I guess no one need to get UPDATED Offline values, because they only change after off-line data collection activities, like I wrote above.

If someone needs it in the future, we can change it.
